### ISSUE TITLE
location table 구성 

### ISSUE THREAD

**Issue by soyoungyi** [ohdsi-korea/ThemisKorea#11]
안녕하세요. location table 구성 관련 문의드립니다. 

1, 시군구정보와 우편번호정보까지 구성하였는지요? 그리고 어떤 필드에 어떤 값을 넣으셨는지요?
2, 또 이런정보들을 영문으로 넣으셨는지 아니면 한글주소로 구성하셨는지도 문의드립니다.

**Comment by JaehyeongCho** [comment]
@soyoungyi 질문에 답변드립니다.

1. OHDSI의 location table은 환자의 개인정보를 보호하기 위해 특별한 이유가 없는 한, 우편번호 앞 3자리까지 (시, 군, 구) 사용하도록 되어있습니다 (즉, 구체적인 시, 군, 구내 일련번호는 마스킹). 이 [기준](https://github.com/OHDSI/CommonDataModel/wiki/LOCATION)에 맞추어 location table을 구성했습니다. 구체적인 값들은 본 repository의 [location table file](https://github.com/ohdsi-korea/ThemisKorea/tree/master/location)을 참조하시면 좋을 것 같습니다.
우편번호는 2015년 8월 1일부터 개정된 [5자리 우편번호](https://www.epost.go.kr/search/zipcode/cmzcd003k01.jsp)를 사용했습니다. 

2. 모든 지역명은 대한민국 영문표기명에 맞게 구성했습니다. 역시 location table을 참조하시면 될 것 같습니다.

충분한 답변이 되셨는지 모르겠습니다.

**Comment by soyoungyi** [comment]
추가질문드립니다~ 

우편번호를 2015년 8월 1일부터 개정된 5자를 우편번호를 사용했다고 하셨는데, 그럼 구주소는 변환하지 않은건가요?

**Comment by JaehyeongCho** [comment]
@soyoungyi 

안녕하세요,

제 답변에 혼란스러우셨을 수 있을 것 같습니다. 죄송합니다. 이전에 다음과 같이 답변을 드렸었습니다:


> 우편번호는 2015년 8월 1일부터 개정된 5자리 우편번호를 사용했습니다.

이 답변은, CDM DB에서 환자가 거주하는 지역을 구분하기 위한 단위 (즉, location_id) 를 구성하기 위해 개정된 우편번호를 기반으로 생성했다는 것을 의미합니다.

우편번호가 개정되기 이전에 의료기관에 내원한 환자는 우편번호 6자리를 가지고 있는게 맞으며, 해당 환자들은 개정된 후의 우편번호가 의미하는 지역에 매핑하여 location_id를 부여하시면 될 것 같습니다.

예) 경기도 수원시 영통구 원천동 산26-6에 거주하는 환자의 경우, 구 우편주소로는 443-721, 신 우편주소로는 16499를 가지지만 location_id는 다음과 같이 부여하게 됩니다:
307		NA	Suwon-si	Gyeonggi-do	164	NA	South Korea	164	37.2824698	126.9740787

해결이 되셨는지요?

**Comment by soyoungyi** [comment]
네 감사합니다 해결 되었습니다~ 

마지막으로 예시를 들어주신결 보면, 구우편이든 신우편이든 똑같이 zip code에  164로 쓴다는 의미이신거죠?

**Comment by chandryou** [comment]
>마지막으로 예시를 들어주신결 보면, 구우편이든 신우편이든 똑같이 zip code에 164로 쓴다는 의미이신거죠?

네, 그게 낫지 않을까 싶습니다 ^^

**Comment by JaehyeongCho** [comment]
> 마지막으로 예시를 들어주신결 보면, 구우편이든 신우편이든 똑같이 zip code에 164로 쓴다는 의미이신거죠?

네 맞습니다.

**Comment by soyoungyi** [comment]
안녕하세요~ 추가 질문이 있어 다시 올립니다. 

예로, 서울시 종로구인 경우는 우편번호 앞3자리가 030~032 로 구성된다고 우체국 사이트에 나와있는데요, (https://www.epost.go.kr/search/zipcode/cmzcd003k01.jsp)
location 테이블은 시, 군, 구 까지 정보로 구성되는데 그럼 위와같이 서울지 종로구와 같은 경우에, zip코드를 뭘로 변환하셨는지 궁금합니다.

**Comment by JaehyeongCho** [comment]
@soyoungyi 
예를 들어, 1번 환자가 03001의 우편번호를 가질 경우, 4번째 자리부터 마스킹된 zipcode 030에 해당하는 location_id인 129를 할당하고, 2번 환자가 03101의 우편번호를 가질 경우, 4번째 자리부터 마스킹된 zipcode 031에 해당하는 location_id인 130을 할당했습니다.

저희가 올린 [location table](https://github.com/ohdsi-korea/ThemisKorea/blob/master/location/location_v6.csv)을 참고하시면 이해하시는데 도움이 될 수 있으리라 생각이 됩니다.

감사합니다.

**Comment by soyoungyi** [comment]
서울시 종로구에는 03000~03299까지 300개의 구역번호(우편번호)가 부여되어 있으며, 실제 사용된 번호는 03000~03198(199개)라고 우체국 사이트에 나와 있는데요,

제가 드린 질문은, 예로 1번환자가 03001이고, 2번환자가 03002, 이런식으로 03099까지 있을텐데, 이 경우  앞자리 3자리가 030으로 모두 동일한데요, 이런경우가 어떻게 되는지 궁금해서 문의드렸습니다~^^

**Comment by JaehyeongCho** [comment]
@soyoungyi 

안녕하세요, 저희의 경우는 하나의 location_id를 부여하기 위한 기준으로, zip code의 앞 3자리를 제외한 나머지 코드가 마스킹된 상태에서의 zip code를 기준으로 하나의 location_id를 부여했습니다.

즉, 03001 ~ 03099의 우편번호를 가지는 환자들의 경우는, zip code를 앞 세 자리만 보았을 때, 모두 030이기 때문에 하나의 location_id를 부여합니다. 저희의 경우, zip code가 030인 경우 location_id 129를 부여했습니다.

만약에 또 다른 환자가 03101을 가지는 경우, 앞 세 자리를 제외하고 마스킹 했을 때, 031이기 때문에 이 경우는 location_id 130을 부여했습니다.

**Comment by SooyoungYoo** [comment]
안녕하세요.

기관별로 '시도'와 '시군구' 정보를 구성하는 필드에 차이가 있어 규칙을 정해서 맞추면 좋을 것 같습니다.
'시도' 정보는 city 필드에 저장되고 있어 이슈가 없는데요. '시군구' 정보는 기관에 따라 state 또는 address_1 필드에 구성되고 있는 것 같습니다.
