### ISSUE TITLE
measurement type concept id 

### ISSUE THREAD

**Issue by soyoungyi** [ohdsi-korea/ThemisKorea#12]
안녕하세요, 
measurement type concept id 는 어떤값을 사용하고 계신가요? 

 - 44818702 : lab result  (검사결과)
 - 44818701 : From physical examination  (임상관관기록지)

찾아보니 위의 두개 코드가 가장 적절할 것 같은데요,  사용하고 있는 다른 measurement type concept id가 있으신지 궁금합니다.

**Comment by choiyoungjin426** [comment]
<p>아주대학교 병원은 ‘44818701:From physical examination’와 ’5001:Test ordered through EHR’을 사용하고 있습니다.<br />
검진 환자의 경우 ’44818701:From physical examination’ 코드를 사용하고 있으며 일반 환자의 경우 모든 검사 결과가 ‘Lab result’라고 판단하기 어려워 ’44818702:Lab result’ 코드 대신 ‘5001:Test ordered through EHR’ 코드를 사용하고 있습니다.</p>

<h1></h1>
<div id="measurement-type-concept-id" class="section level4">
<h4>Measurement Type Concept id</h4>
<table style="width:100%;">
<colgroup>
<col width="12%"></col>
<col width="20%"></col>
<col width="16%"></col>
<col width="16%"></col>
<col width="16%"></col>
<col width="16%"></col>
</colgroup>
<thead>
<tr class="header">
<th>ID</th>
<th align="left">NAME</th>
<th align="left">CLASS</th>
<th align="left">CONCEPT</th>
<th align="left">DOMAIN</th>
<th align="left">VOCAB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>‘5001’</td>
<td align="left">Test ordered through EHR</td>
<td align="left">‘Meas Type’</td>
<td align="left">‘Standard’</td>
<td align="left">‘Type Concept’</td>
<td align="left">‘Meas Type’</td>
</tr>
<tr class="even">
<td>‘44818701’</td>
<td align="left">From physical examination</td>
<td align="left">‘Meas Type’</td>
<td align="left">‘Standard’</td>
<td align="left">‘Type Concept’</td>
<td align="left">‘Meas Type’</td>
</tr>
<tr class="odd">
<td>‘44818702’</td>
<td align="left">Lab result</td>
<td align="left">‘Meas Type’</td>
<td align="left">‘Standard’</td>
<td align="left">‘Type Concept’</td>
<td align="left">‘Meas Type’</td>
</tr>
</tbody>
</table>
<p>추가로 다음 <a href="http://athena.ohdsi.org/search-terms/terms?domain=Type+Concept&amp;standardConcept=Standard&amp;vocabulary=Meas+Type&amp;page=1&amp;pageSize=15&amp;query=">URL</a>을 참조하시면 더 좋을 것 같습니다.</p>
</div>

**Comment by soyoungyi** [comment]
추가 질문 드립니다~ 

그럼, 검진환자와 일반환자만 구분하고, 임상관찰기록지에나오는 항목들도 모두 저 2가지 코드로만 구분하시는지 추가 문의드립니다.

**Comment by chandryou** [comment]
@soyoungyi 네 현재로써는 그렇게 하고 있습니다. 
혹시 더 좋은 의견 있으시면 말씀해주세요 ^^

**Comment by soyoungyi** [comment]
방문에서도 검진환자는 구분하지 않는다는 내용이 있던데, 굳이 검사결과에서 검진환자를 구분하신 환자가 있으신지요? 

그리고, 저희 기관에서는 
- 44818702 : Lab result(검사결과)
- 44818701 : From physical examination(임상관찰기록)
- 45754907 : Derived value
- 32423 : NLP derived(NLP처리해서 넣은 항목)

이렇게 사용하고 있습니다.
