### ISSUE TITLE
CONDITION_OCCURRENCE 용어 mapping 관련 

### ISSUE THREAD

**Issue by SooyoungYoo** [ohdsi-korea/ThemisKorea#17]
안녕하세요.

Condition_occurrence.condition_concept_id는 condition 도메인의 용어로 매핑되어야 하는 것으로 되어 있기는 한데요. 원내 진단명 중에는 condition 도메인으로 매핑되지 않는 용어들도 있어, 다른 도메인으로 매핑되는 진단명을 어떻게 처리하셨는지 문의드립니다.

예를 들어, 저희는 Liver donor 라는 원내 진단명이 ICD-10 코드로는 Z52.6 (Liver donor)으로 매핑되어 있고, SNOMED CT로는 concept_id 4023154 (Donor for liver transplant, Observation domain)로 매핑되어 있습니다.

다른 도메인으로 매핑되는 진단명을 해당 도메인의 테이블로 저장해도 되지만, ICD 또는 KCD 코드를 기준으로 연구를 하는 경우 진단명이 여러 테이블에 저장될 수 있다는 점을 고려해서 연구 디자인을 해야 될 것 같아 다른 병원들은 어떻게 처리하고 계신지 궁금합니다. KCD 코드를 활용하려면 아무래도 모든 진단명을 condition_occurrence 테이블에 저장하는 게 편리한데 매핑 도메인이 문제되는 것 같습니다.

감사합니다.

**Comment by chandryou** [comment]
>KCD 코드를 활용하려면 아무래도 모든 진단명을 condition_occurrence 테이블에 저장하는 게 편리한데 매핑 도메인이 문제되는 것 같습니다.

@SooyoungYoo 교수님, 안타깝지만 해당 문제에 대한 OHDSI의 방침은 명확합니다. 
Z52.6이 observation domain의 concept으로 mapping 된다면, observation으로 변환하라 입니다.
(domain 은 언제나 지켜져야 합니다.)

디른 모든 나라가 이렇게 하고 있기 때문에, 한국만 다른 방침을 적용한다면 다국적 연구에서 문제가 생길 것 같습니다. 
공단 데이터 ETL시에는 이러한 방침에 따라 ETL을 진행했었습니다 (https://github.com/ABMI/ETL--Korean-NSC/tree/youngjin/etlKoreanNSC/inst/sql/sql_server)

큰 도움이 되지 못하여 죄송합니다.

**Comment by SooyoungYoo** [comment]
답변 감사합니다. 
진단 코드의 경우, condition이 아닌 다른 도메인으로 매핑되는 경우 다른 테이블에 저장하지 않고 condition_concept_id를 0으로 처리하여 condition_occurrence 테이블에 저장하는 방법도 있을 것 같은데요.
아주대학교에서는 매핑이 되는 도메인으로 각각 저장을 하셨는지, 혹은 비매핑으로 변환하셨는지요?

**Comment by SooyoungYoo** [comment]
CDM 원칙 상 condition_occurrence 테이블에는 순수하게 질병으로 볼 수 있는 데이터만 저장되어야 하기 때문에, KCD 코드 중에 condition이 아닌 다른 도메인으로 매핑된 코드들은 해당 테이블에 저장해야 되는 것으로 확인하였습니다. 감사합니다.

**Comment by chandryou** [comment]
@SooyoungYoo  예 맞습니다. 감사합니다.
