### ISSUE TITLE
[ATLAS] Concept sets에 장바구니를 이용하여 concept 추가 시, 오류가 발생합니다 

### ISSUE THREAD

**Issue by dianakim44** [ohdsi-korea/ThemisKorea#18]
안녕하세요,
가톨릭대학교 의료정보학교실 연구원 김동민입니다

현재, 지난 아주대 ATLAS 데이터톤에서 배웠던 것을
저희 서버 ATLAS에서 적용을 하고있는 중입니다

그런데 적용과정에서
다음과 같은 문제가 발생하여 질문드립니다..!

아래 사진과 같이 test concept sets을 만든 후,
새로운 concept 을 추가하는 작업 중에 있습니다

![image](https://user-images.githubusercontent.com/29847295/65477896-b567a100-dec2-11e9-93a6-49d86bde1dec.png)

그런데, 위 그림처럼 _① 장바구니를 클릭_하고
다시 상단 _② test concept set을 클릭_하면,
다음 스크린 샷과 같이 에러가 뜹니다 ㅠ

![image](https://user-images.githubusercontent.com/29847295/65477705-1b9ff400-dec2-11e9-875e-63ac176e1fa5.png)

혹시 이 문제를 동일하게 겪으셨거나 해결방안을 아시는지요..?

답변주시면 감사하겠습니다!
김동민 드림

**Comment by JaehyeongCho** [comment]
@dianakim44 

안녕하세요, 아주대학교 의료정보학과 조재형입니다.

해당 에러는 webapi build 하면서 생긴 에러가 아닐까 싶습니다. 에러가 생겼을 때, f12를 눌렀을 때 발생하는 에러를 보시면 해결방안을 찾을 수 있지 않을까 싶습니다. 설치하신 개발팀과 상의하시거나, 재설치를 하시면 빠르게 해결 할 수 있을 것 같습니다.

만약 해결이 잘 안되시면, 에러를 남겨주시길 바라겠습니다.

조재형 드림
