### ISSUE TITLE
4개병원 ETL 정의서 공유드립니다.

### ISSUE THREAD

**Issue by soyoungyi** [ohdsi-korea/ThemisKorea#20]
안녕하세요 분당서울대학교병원 이소영입니다. 

분당서울대학교병원, 서울대학교병원, 서울아산병원, 카톨릭대학교 서울성모병 간에 논의해서 정리한  ETL 정의서를  공유드립니다. 추가 논의된 내용은 파일의 version으로 표기하여 업로드하도록 하겠습니다. 많은 참고 부탁드립니다.
 
[4개병원_ETL정의서_v1.xlsx](https://github.com/ohdsi-korea/ThemisKorea/files/4126900/4._ETL._v1.xlsx)

**Comment by chandryou** [comment]
@soyoungyi [Wiki](https://github.com/ohdsi-korea/ThemisKorea/wiki)에 업로드하여 공유였습니다. 정말 감사드립니다 ^^
