### ISSUE TITLE
Provider의 Concept ID 의 조화를 위한 질문

### ISSUE THREAD

**Issue by DJChang** [ohdsi-korea/ThemisKorea#21]
안녕하세요, 여의도성모병원 안과의 장동진이라고 합니다. 

https://github.com/ohdsi-korea/ThemisKorea/wiki/Suggestion-for-the-PROVIDER-table 의 원칙을 준수하며, 가톨릭중앙의료원의 Provider의 concept ID를 수정하던 도중, 다음을 논의드리고자 합니다. 

1. 누락된 과
일부과는 그 기능이 비슷해보이나 그 명칭이 엄연히 다릅니다.
(호흡기알레르기 내과 == 호흡기내과?, 혈액종양내과 == 혈액내과? 종양내과?)
또한 일부과는 특정병원에만 존재하는 과가 있습니다. (예방의학과, 완화의학과, 작업환경의학과 등)
치과 또한 포함되어 있지 않습니다. 

이들 과의 경우 위 리스트에 추가하는 것이 어떤가 합니다. 

진료과 | 진료과 영문 | concept_id | concept_name
-- | -- | -- | --
호흡기알레르기내과 | Pulmonology and Allergy | 38004472 | Pulmonary Disease
종양내과 | Medical oncology | 38004507 | Medical Oncology
혈액내과 | Clinical hematology | 38004501 | Hematology
호흡기알레르기내과 | Allergy/Immunology | 38004448 | Allergy/Immunology
예방의학과 | Preventive medicine | 38004503 | Preventive Medicine
완화의학과 | Palliative medicine | 44777682 | Palliative medicine
직업환경의학과 | Occupational and Environmental medicine | 38003974 | Preventive Medicine/Occupational Environmental Medicine
임상약리과 | Clinical pharmacology and Therapeutics | 38004025 | Clinical pharmacology
치과 | Dental medicine specialties | 903277 | Dentistry

2. 외과의 세부전공
위 원칙에 따르면 외과의 세부전공은 모두 General Surgery로 매핑하면 좋을 듯 하나, 일부 과는 세부전공의 
Concept ID가 이미 존재하고 있습니다.(대장항문외과, 소아외과, 혈관이식외과)

최대한 자세히 기록하여 두는 것이 나중에 연구 및 질관리에 도움이 될 듯 하여 선호됩니다만, General Surgery로 상위개념 매핑을 할지, 아니면 다른과의 Concept ID를 생성 요청하여 세세하게 가는 것이 좋을지 의견을 여쭙니다. 

진료과 | 진료과 영문 | concept_id | concept_name
-- | -- | -- | --
대장항문외과 | Colorectal surgery | 38004471 | Colorectal Surgery
소아외과 | Pediatric surgery | 45756819 | Pediatric Surgery
혈관이식외과 | Vascular and transpland surgery | 38004496 | Vascular Surgery
위장관외과 | Stomach surgery | 38004447 | General Surgery
유방외과 | Breast surgery | 38004447 | General Surgery
갑상선내분비외과 | Thyroid Endocrine surgery | 38004447 | General Surgery
간담췌외과 | Pancreatobiliary surger | 38004447 | General Surgery
중환자외상외과 | Acute care surgery | 38004447 | General Surgery

감사합니다.

**Comment by chandryou** [comment]
@DJChang 교수님 감사합니다. 
1번 이슈: 누락된 과에서 non-standard concept인 경우 standard로 다시 찾았고, 이미 기재되어 있는 과를 제외하고 반영하였습니다. (https://github.com/ohdsi-korea/ThemisKorea/wiki/Suggestion-for-the-PROVIDER-table/2ccb261d27fba3fdb8d057dffbbf358093bfe3e1)

**Comment by chandryou** [comment]
@DJChang  교수님 2번 코멘트에 맞춰 [provider table](https://github.com/ohdsi-korea/ThemisKorea/wiki/Suggestion-for-the-PROVIDER-table)을 업데이트 하였습니다. 
모두 General surgery의 하위 concept 들이기 때문에- 쉽게 사용하실 수 있을 것 같습니다 (다만 정형외과/신경외과도 GS의 하위 concept 이라는 점을 유념하시기 바랍니다.)

혈관이식외과/중환자외상외과의 경우 두 개의 specialty가 합쳐진 과인데, 임의로 이식외과와 외상외과만을 남겼습니다. 1번 원칙에 맞춰 이식외과와 외상외과로 mapping 해주시면 어떨까 합니다 (혹시 이견 있으시면 말씀해주세요 ^^)

다른 건 모두 찾았는데, general surgery 하위 concept으로 갑상선내분비외과에 합당한 용어는 찾지 못하였습니다.. 

노고에 감사드립니다.

**Comment by chandryou** [comment]
PROVIDER table page 링크 주소가 바뀌었습니다. ^^
https://github.com/ohdsi-korea/ThemisKorea/wiki/PROVIDER
