### ISSUE TITLE
PGHD to CDM 변환 가이드라인 제안(공개)

### ISSUE THREAD

**Issue by HIRC-SNUBH** [ohdsi-korea/ThemisKorea#26]
안녕하세요.
분당서울대학교병원 헬스케어 ICT 연구소 입니다.

Patient-Generated Health Data (PGHD)를 OMOP (Observation Medical Outcomes Partnership) CDM (Common Data Model) 으로 변환하기 위한 규칙 및 표준 용어 매핑 정보를 정리하였으며, 이를 가이드라인 문서로 제안하고자 합니다.

본 가이드라인이 분당서울대학교병원에서 사용하는 PHR app.과 건강검진설문조사지를 기반으로 작성되었으나, 향후 보다 많은 종류의 PGHD 항목들을 포함하기 위해 고도화가 필요할 것이며 이에 대한 협력이 필요할 것으로 생각하고 있습니다.

아래 github에 공개되어 있는 문서를 참고하셔서 PGHD to CDM 변환에 도움이 되시길 바라며, 수정 및 보완이 필요한 부분이 있다면 편하게 제안 부탁드립니다.

https://github.com/HIRC-SNUBH/PGHD_conversion_guide/blob/main/README.md

> 이 연구는 2019년도 산업통상자원부 및 산업기술평가관리원(KEIT) 연구비 지원에 의한 연구임 (No.20004927, CDM 기반 바이오헬스데이터 통합 플랫폼 고도화 및 검증 기술개발)

**Comment by chandryou** [comment]
감사합니다! 이 내용을 WiKi에도 반영하도록 하겠습니다.

**Comment by chandryou** [comment]
https://github.com/ohdsi-korea/ThemisKorea/wiki
