### ISSUE TITLE
병리결과 입력 방법

### ISSUE THREAD

**Issue by chandryou** [ohdsi-korea/ThemisKorea#3]
병리결과에 예를들어 Positive/Negative같이 정량적으로 보고가 되는 데이터는 Measurement에 넣나요?
병리결과는 Text여서 아산에서는 Note 테이블에 일단 데이터를 넣었는데 NLP로 처리하면 Measurement로 넣어야 하나 궁금합니다.

**Comment by chandryou** [comment]
먼저 현재 진행 중이지만 [Oncology CDM Proposal](https://github.com/OHDSI/CommonDataModel/issues/239)을 참고해보셔야 할 것 같습니다.

현재의 Proposal 대로라면 병리 텍스트 중 정리된 데이터는 Measurement 로 들어가게 되어 있습니다.
(Measurement type concept id = 32423)

**Comment by Jimyung6642** [comment]
NOTE 테이블에는 비정형 free text 데이터가 입력되는 것으로 정의되어있습니다. 
(https://github.com/OHDSI/CommonDataModel/wiki/NOTE)

그렇기 때문에 NLP 로 가공된 데이터라면 Measurement, Observation, Note_NLP 등의 다른 테이블로 넣는 것이 바람직해보입니다.
