### ISSUE TITLE
병리보고서 pathology stage와 subtype의 concept_id

### ISSUE THREAD

**Issue by na1004dang** [ohdsi-korea/ThemisKorea#9]
안녕하세요. 
현재 병리보고서를 자연어처리하며 pathology stage(TNM stage)와 subtype을 추출하여 concept_id를 부여하려고 합니다.
현재 아래 첨부하는 사진과 같이 concept_id를 찾았는데 다른곳에서는 어떤 concept_id를 사용하는지 궁금합니다.
컨셉의 도메인과 클래스를 어떤것으로 사용하는지 문의드립니다.
'Condition' or 'Observation'
'Clinical Finding' or 'Morph Abnormality'

<img width="757" alt="tnm stage" src="https://user-images.githubusercontent.com/6101028/62099597-946f3f00-b2c9-11e9-90ed-3a2c34a34310.PNG">
<img width="1012" alt="subtype_concept_id" src="https://user-images.githubusercontent.com/6101028/62099608-989b5c80-b2c9-11e9-8ef0-e067e9c7d5fa.PNG">

**Comment by neal1202** [comment]
안녕하세요.  
현재 논의 중인 Oncology extension CDM에서는 histology와 topography 정보를 이용한 ICD-O-3 code를 cancer에 대한 concept_id를 생성하여 SNOMED의 clinical finding으로 매핑하고있습니다. 
첨부한 proposal 및 ICD-O-3를 SNOMED로 ETL시 지침에서는 Histology를 ICD-O-3 code에 포함시켜 
![image](https://user-images.githubusercontent.com/47546151/62434473-654a4900-b773-11e9-98f1-948a161393ca.png) 와 같은 condtion source concept_id를 생성하여,
![image](https://user-images.githubusercontent.com/47546151/62434349-f79e1d00-b772-11e9-8d24-f159267870ce.png)와 같은 SNOMED CODE에 mapping 하여 구성하는 예가 있습니다. 

또한 TNM staging 의 경우도 해당 확장 모델에서 NAACCR vocabulary를 이용하여 Measurement  domain에 enroll하고 있으므로 이 또한 참고 부탁 드립니다. 

[Oncology working group github](https://github.com/OHDSI/OncologyWG)

[ICD-O-3를 SNOMED로 ETL시 지침](https://github.com/OHDSI/OncologyWG/wiki/ETL-Instructions-for-Mapping-ICDO-to-SNOMED)

[Oncology CDM Proposal 18-11-15.pdf](https://github.com/ohdsi-korea/ThemisKorea/files/3454994/Oncology.CDM.Proposal.18-11-15.pdf)

**Comment by na1004dang** [comment]
안녕하세요. 등록해주신 답변을 기반으로 oncology working group을 확인중에 있습니다.
감사합니다.
확인하면서 한가지 여쭤보고싶은건 TNM stage의 경우 제가 질문에 첨부한 캡쳐와 같이 Clinical Finding, condition으로 기재하고 있습니다.
condition의 경우 measurement 테이블로 어떻게 extension할 수 있는지 확인부탁드리겠습니다.

**Comment by na1004dang** [comment]
안녕하세요. 
답변주신 부분에 대해 확인하여 다음과 같이 정리하게 되었습니다.
병리보고서에서 추출된 Subtype 정보
 - 'CONDITION_OCCURRENCE' 테이블에 수록
 - condition source concept_id : histology와 topography 정보가 포함되는 ICD-O-3 code 부여
 - condition concept_id : condition source concept_id의 SNOMED code 부여

병리보고서에서 추출된 TNM Stage 정보 및 그 외 항목들
 - 'MEASUREMENT' 테이블에 수록
 - MODIFIER_OF_EVENT_ID와 MODIFIER_FIELD_CONCEPT_ID를 이용하여 CONDITION_OCCURRENCE의 extension table로 활용
 - TNM Path T, N, M 각각의 value concept_id를 NAACCR vocabulary로매핑하여 수록

답변주셔서 감사합니다.

**Comment by neal1202** [comment]
Oncology extension 모델에서 제안된 바와 동일하게 수록된 것 같습니다. 감사합니다.
